snow-golems:
  health: 8.0

nuclear-ghasts:
  enabled: true
  spawn-chance: 0.01
  fireballs:
    explosion:
      power: 4.0
      set-fire: true
      break-blocks: true
  death:
    explosion:
      enabled: true
      power: 5.5
      set-fire: true
      break-blocks: true
    poison:
      enabled: true
      potency: 3
      duration-seconds: 15
      lingering: true

ur-ghasts:
  enabled: true
  spawn-chance: 0.02
  extra-scale: 1.00
  extra-health: 70
  extra-detection-range: 300
  fireballs:
    explosion:
      power: 4.0
      set-fire: true
      break-blocks: true

projectiles:
  snowball:
    damage: 1.0
    snowman-snowball:
      damage: 1.0
      slowness:
        enabled: true
        potency: 3
        duration-seconds: 15
      blindness:
        enabled: true
        potency: 3
        duration-seconds: 15
  egg:
    damage: 1.0
  fire-charge:
    throwing:
      enabled: true
      hunger-consumption: 1
    speed: 2.0
  ghast-fireball:
    craftable: true
    throwing:
      enabled: true
      hunger-consumption: 2
    speed: 3.0
